# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (username.github.io) then use these settings:
url: "https://blog.mphomphego.co.za"
#url: "https://mmphego.github.io"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Name of website
title: Mpho Mphego

#For my changes
# use meta-title: for the center heading of the page.
# use title: to set the <title> of the web page.
# use subtitle: to set the sub heading for that title(meta-title). NOTE: if(meta-title exists){subtilel visiblity = true}

# Short description of your site
description: Welcome to the geek side!

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  # About Me: "/aboutme.html"
  # Projects: "/projects.html"
  # Expedition: ""
  Resume: "resume/MphoMphego.pdf"
  Tags: "tags"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/main.jpg"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter. The logo will have a height of 40px
# title-img: /path/to/image

# # --- Background colour/image options --- #

# By default, the navigation bar and footer have a light gray background, and the main page
# has a white background. You can specify a different background colour or a background image
# for the navigation bar, the main page, and the footer.
# navbar-col: "orange"
# navbar-img: "/img/bgimage.png"
# footer-col: "blue"
# footer-img: "/img/bgimage.png"
# page-col: "#FF0000"
# page-img: "/img/bgimage.png"

# # --- Footer options --- #

# # Change all these values or delete the ones you don't want.
# # Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Mpho Mphego
# email:
  # facebook:
  github: mmphego
  # twitter:
  # google-plus:
  linkedin: mphomphego
  stackoverflow: 6165344/mpho-mphego
  # instagram:
# reddit: yourname
# xing: yourname
# snapchat: yourname
  youtube: xxXMphoXxx
# spotify: yourname
# steam: yourname
# twitch: yourname
# yelp: yourname

# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: false
  email: false
  twitter: false
  google-plus: false
  github: true
  linkedin: true
  stackoverflow: true
  instagram: false
  reddit: false
  xing: false
  snapchat: false
  youtube: true
  spotify: false
  steam: false
  twitch: false
  yelp: false

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: true
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "mphomphego.co.za"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "mmphego-github-io"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-68808612-1"

# Google Tag Manager ID
gtm: "GTM-PDCDJZ3"

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Africa/Johannesburg"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  #     disable : true
highlighter: rouge
permalink: /blog/:year/:month/:day/:title.html
paginate: 10


# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
  - _site

#Meta data for your Posts
metadata:
  _posts:
    - name: "layout"
      field:
        element: "hidden"
        value: "post"
    - name: "title"
      field:
        element: "text"
        label: "Post title"
        placeholder: "Title"
        alterable: true
    - name: "subtitle"
      field:
        element: "textarea"
        label: "Subtitle"
        placeholder: "A description of your post."
        alterable: true
    - name: "date"
      field:
        element: "text"
        label: "Date"
        help: "Enter date of post."
        placeholder: "yyyy-mm-dd"
        alterable: true
    - name: "image"
      field:
        element: "text"
        label: "Image"
        help: "Add a thumbnail image to your post."
        placeholder: "Thumbnail"
        alterable: true
    - name: "published"
      field:
        element: "checkbox"
        label: "Publish"
        help: "Check to publish post, uncheck to hide."

jekyll-archives:
  enabled: 'all'
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-categories
  - jekyll-archives

