name: Jekyll site CI
on:
  push:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:4.2.2 \
        /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

    - name: Trigger Second Workflow
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO2_ACCESS_TOKEN }}
        repository: mmphego/mmphego
        event-type: trigger-latest-blog-post-workflow
