name: Jekyll site CI
on:
  push:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:3@sha256:96a7e98a84f1aeea0b3ab7ff144fd4b6d5a1fa9c4ee690b00a873c895e0793bb \
        /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

    - name: Trigger Second Workflow
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO2_ACCESS_TOKEN }}
        repository: mmphego/mmphego
        event-type: trigger-latest-blog-post-workflow
