name: Jekyll site CI
# https://github.com/marcnuri-demo/actions-remote-dispatch-b/blob/master/.github/workflows/pong.yml
on:
  push:

  repository_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:3 /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

    # - name: PING - Trigger Workflow event
    #     if: github.event.action != 'pong'
    #     run: |
    #       curl -X POST https://api.github.com/repos/mmphego/mmphego/dispatches \
    #       -H 'Accept: application/vnd.github.everest-preview+json' \
    #       -u ${{ secrets.PT_TOKEN }} \
    #       --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
    #   - name: ACK - Acknowledge pong from remote repository
    #     if: github.event.action == 'pong'
    #     run: |
    #       echo "PONG received from '${{ github.event.client_payload.repository }}'" && \
    #       curl -X POST https://api.github.com/repos/mmphego/mmphego/dispatches \
    #       -H 'Accept: application/vnd.github.everest-preview+json' \
    #       -u ${{ secrets.PT_TOKEN }} \
    #       --data '{"event_type": "ack", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
